<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Hydrator\HydratorException;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AppDocumentUserHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate(object $document, array $data, array $hints = array()): array
    {
        $hydratedData = array();

        /** @Field(type="int") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['id']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="collection") */
        if (isset($data['roles']) || (! empty($this->class->fieldMappings['roles']['nullable']) && array_key_exists('roles', $data))) {
            $value = $data['roles'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['roles']['type'];
                $return = $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['roles']->setValue($document, $return);
            $hydratedData['roles'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['username']) || (! empty($this->class->fieldMappings['username']['nullable']) && array_key_exists('username', $data))) {
            $value = $data['username'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['username']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['username']->setValue($document, $return);
            $hydratedData['username'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['discriminator']) || (! empty($this->class->fieldMappings['discriminator']['nullable']) && array_key_exists('discriminator', $data))) {
            $value = $data['discriminator'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['discriminator']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['discriminator']->setValue($document, $return);
            $hydratedData['discriminator'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['avatarUrl']) || (! empty($this->class->fieldMappings['avatarUrl']['nullable']) && array_key_exists('avatarUrl', $data))) {
            $value = $data['avatarUrl'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['avatarUrl']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['avatarUrl']->setValue($document, $return);
            $hydratedData['avatarUrl'] = $return;
        }

        /** @Field(type="collection") */
        if (isset($data['discordRoles']) || (! empty($this->class->fieldMappings['discordRoles']['nullable']) && array_key_exists('discordRoles', $data))) {
            $value = $data['discordRoles'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['discordRoles']['type'];
                $return = $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['discordRoles']->setValue($document, $return);
            $hydratedData['discordRoles'] = $return;
        }
        return $hydratedData;
    }
}